// <auto-generated />
using System;
using System.Collections.Generic;
using Intervue.Domain.ValueObjects;
using Intervue.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intervue.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IntervueDbContext))]
    [Migration("20260309171601_AddPromptProfileToInterview")]
    partial class AddPromptProfileToInterview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intervue.Domain.Entities.CvProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("cv_profiles", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("CvProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CvProfileId");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.FeedbackReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<IReadOnlyList<InterviewScore>>("CategoryScores")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InterviewId")
                        .HasColumnType("uuid");

                    b.Property<int>("OverallScore")
                        .HasColumnType("integer");

                    b.Property<string>("Strengths")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Weaknesses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId")
                        .IsUnique();

                    b.ToTable("feedback_reports", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CvProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptProfile")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.InterviewMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InterviewId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId");

                    b.ToTable("interview_messages", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CvProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.PrimitiveCollection<string>("TechnologiesUsed")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CvProfileId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CvProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CvProfileId");

                    b.ToTable("technologies", (string)null);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.CvProfile", b =>
                {
                    b.OwnsOne("Intervue.Domain.ValueObjects.HashedPersonalData", "HashedPersonalData", b1 =>
                        {
                            b1.Property<Guid>("CvProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hashed_personal_data");

                            b1.HasKey("CvProfileId");

                            b1.ToTable("cv_profiles");

                            b1.WithOwner()
                                .HasForeignKey("CvProfileId");
                        });

                    b.Navigation("HashedPersonalData")
                        .IsRequired();
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Experience", b =>
                {
                    b.HasOne("Intervue.Domain.Entities.CvProfile", null)
                        .WithMany("Experiences")
                        .HasForeignKey("CvProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.FeedbackReport", b =>
                {
                    b.HasOne("Intervue.Domain.Entities.Interview", null)
                        .WithOne("FeedbackReport")
                        .HasForeignKey("Intervue.Domain.Entities.FeedbackReport", "InterviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.InterviewMessage", b =>
                {
                    b.HasOne("Intervue.Domain.Entities.Interview", null)
                        .WithMany("Messages")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Project", b =>
                {
                    b.HasOne("Intervue.Domain.Entities.CvProfile", null)
                        .WithMany("Projects")
                        .HasForeignKey("CvProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Technology", b =>
                {
                    b.HasOne("Intervue.Domain.Entities.CvProfile", null)
                        .WithMany("Technologies")
                        .HasForeignKey("CvProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Intervue.Domain.Entities.CvProfile", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Projects");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("Intervue.Domain.Entities.Interview", b =>
                {
                    b.Navigation("FeedbackReport");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
